dist: xenial
language: ruby
rvm:
- 2.5.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - R_LIBS_USER=~/R/Library
    - R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library

cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - $R_LIBS_USER

before_script:
  - chmod +x bin/make_index.sh
  - chmod +x bin/make_members_feeds.sh
  - chmod +x bin/make_workshop_feeds.sh
  - chmod +x bin/make_newsletter_feed.sh

before_install:
  - sudo add-apt-repository -y "ppa:marutter/rrutter3.5"
  - sudo add-apt-repository -y "ppa:marutter/c2d4u3.5"
  - sudo add-apt-repository -y "ppa:ubuntugis/ppa"
  - sudo add-apt-repository -y "ppa:cran/travis"
  - travis_apt_get_update
  - sudo apt-get install -y --no-install-recommends build-essential gcc g++ libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libicu-dev cdbs qpdf texinfo libssh2-1-dev gfortran jq python3.5 python3-pip
  - curl -fLo /tmp/R-3.6.0-$(lsb_release -cs).xz https://travis-ci.rstudio.org/R-3.6.0-$(lsb_release -cs).xz
  - tar xJf /tmp/R-3.6.0-$(lsb_release -cs).xz -C ~
  - export PATH=${TRAVIS_HOME}/R-bin/bin:$PATH
  - export LD_LIBRARY_PATH=${TRAVIS_HOME}/R-bin/lib:$LD_LIBRARY_PATH
  - rm /tmp/R-3.6.0-$(lsb_release -cs).xz
  - sudo mkdir -p /usr/local/lib/R/site-library $R_LIBS_USER
  - sudo chmod 2777 /usr/local/lib/R /usr/local/lib/R/site-library $R_LIBS_USER
  - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile.site
  - export R_PROFILE=~/.Rprofile.site
  - curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz
  - tar xzf /tmp/texlive.tar.gz -C ~
  - export PATH=${TRAVIS_HOME}/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self
  - curl -fLo /tmp/pandoc-2.2-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-1-amd64.deb
  - sudo dpkg -i /tmp/pandoc-2.2-1-amd64.deb
  - sudo apt-get install -f
  - rm /tmp/pandoc-2.2-1-amd64.deb
  - Rscript -e "install.packages(setdiff(c('countrycode', 'gh', 'jsonlite', 'maps','readr','dplyr','tidyr','plotly', 'purrr', 'ggplot2','htmlwidgets','svglite'), installed.packages())); update.packages(lib.loc = Sys.getenv('R_LIBS_USER'), ask = FALSE, checkBuilt = TRUE)"
  - Rscript -e 'sessionInfo()'
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --user numpy scipy matplotlib ipython jupyter pandas

# Assume bundler is being used, therefore
# # the `install` step will run `bundle install` by default.
script:
 - make everything

 after_success:
  cat lesson_contributor_count.json

# # branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=AKIAIBW6BTQUUTKCF5YA
  - export AWS_SECRET_ACCESS_KEY=$S3_SECRET

deploy:
  skip_cleanup: true
  provider: script
  script: aws s3 sync _site s3://feeds.carpentries.org --delete --exclude "*.xml" --exclude "404.html"
