language: ruby
rvm:
- 2.2.5


addons:
  apt:
    packages:
    - python3-requests
    - python3-yaml
    - jq

before_script:
 - chmod +x ./bin/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# # the `install` step will run `bundle install` by default.
script:
 - make everything

# # branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIBW6BTQUUTKCF5YA
  secret_access_key: $S3_SECRET
  bucket: amydata.carpentries.org
  local-dir: _site
  upload-dir: amy
  acl: public_read
