language: ruby
rvm:
- 2.5.3

addons:
  apt:
    packages:
    - jq

# Assume bundler is being used, therefore
# # the `install` step will run `bundle install` by default.
script:
 - make everything

# # branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=AKIAIBW6BTQUUTKCF5YA
  - export AWS_SECRET_ACCESS_KEY=$S3_SECRET

deploy:
  skip_cleanup: true
  provider: script
  script: aws s3 sync _site s3://feeds.carpentries.org --delete --exclude "*.xml" --exclude "404.html"
